#!/usr/bin/env python

import bs4
import requests


machines_url = 'https://db.debian.org/machines.cgi'

response = requests.get(machines_url)
soup = bs4.BeautifulSoup(response.text)

machine_entries = soup.find_all('tr')

for machine_entry in machine_entries:
    machine_data = machine_entry.find_all('td')
    try:
        purpose = machine_data[3].text.strip()
        if purpose == 'porterbox':
            hostname = machine_data[0].text.strip()
            architecture = machine_data[1].text.strip()
            print('%-18s %s' % (architecture, hostname))

    except IndexError:
        # malformed entry, skip it
        pass
